import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { Montserrat, Poppins } from "next/font/google";
import Footer from "@/components/footer/footer";
import { authOptions } from "@/lib/nextAuth";
export const metadata: Metadata = {
  title: "Psychodietetyka, trener żywienia | Złoty środek",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--montserrat",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800','900'],
  display: 'swap',
  preload: true,
  variable: "--poppins"
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="pl" className={`${montserrat.variable} ${poppins.variable}`}>
      <body>
        <Providers session={session}>
          <Navbar />
          <main className="container">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
